/**:
  ros__parameters:
    image_topic: "/camera/hero/front/image"   # Image topic to subscribe to
    lidar_topic: "/carla/hero/lidar"
    weights_file: "weights/yolov4_1_3_416_416_static.onnx"  # Path to ONNX weights file
    lidar_frame: "hero/lidar"
    camera_frame: "hero/front"
    base_frame: "hero"
    confidence_threshold: 0.5  # Confidence threshold for detections
    iou_threshold: 0.4  # IoU threshold for filtering overlapping boxes
    fx: 320.0 
    fy: 320.0
    cx: 320.0
    cy: 240.0
    k_near: 10
    grid_x: 50
    grid_y: 10
    resolution: 0.1
