/**:
  ros__parameters:
    image_topic: "/camera/image_raw"   # Image topic to subscribe to
    weights_file: "weights/yolov4_1_3_416_416_static.onnx"  # Path to ONNX weights file
    lidar_frame: ""
    camera_frame: ""
    confidence_threshold: 0.5  # Confidence threshold for detections
    iou_threshold: 0.4  # IoU threshold for filtering overlapping boxes
    fx: 
    fy:
    cx: 208
    cy: 208
    k_near: 10
